@echo off
setlocal

echo /* WARNING this file is autogenerated for a number of ports by */
echo /* gen_ohboyver.[bat^|sh] */
echo /*
date /t
time /t
echo.
hg log -rtip
echo */

for /f "tokens=*" %%a in (
'date /t'
) do (
set OHBOY_VER=%%a
)
:: NOTE Windows date format  is not controlable via command line like Unix :-(
echo #define OHBOY_VER "%OHBOY_VER%"

endlocal
